modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="more_vanilla"
version="1"
displayName="More Vanilla"
displayURL="https://www.youtube.com/channel/UCK_rI1QIxgwn5kd0UoYvbEQ"
credits="https://www.youtube.com/channel/UCK_rI1QIxgwn5kd0UoYvbEQ"
authors="The DEMON"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.more_vanilla]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration