
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.more_vanilla.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.more_vanilla.MoreVanillaMod;

public class MoreVanillaModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, MoreVanillaMod.MODID);
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> THE_DEMO_NMOD = REGISTRY.register("the_demo_nmod",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.more_vanilla.the_demo_nmod")).icon(() -> new ItemStack(MoreVanillaModItems.ENDERITEINGOT.get())).displayItems((parameters, tabData) -> {
				tabData.accept(MoreVanillaModItems.EAUREGENERANTE_BUCKET.get());
				tabData.accept(MoreVanillaModItems.ADAPAXEL.get());
				tabData.accept(MoreVanillaModItems.ADAPAXELSTONE.get());
				tabData.accept(MoreVanillaModItems.ADAPAXELIRON.get());
				tabData.accept(MoreVanillaModItems.ADAPAXELGOLD.get());
				tabData.accept(MoreVanillaModItems.ADAPAXELDIAMOND.get());
				tabData.accept(MoreVanillaModItems.ADAPAXELNETHERITE.get());
				tabData.accept(MoreVanillaModItems.WOODENHAMMER.get());
				tabData.accept(MoreVanillaModItems.STONEHAMMER.get());
				tabData.accept(MoreVanillaModItems.IRONHAMMER.get());
				tabData.accept(MoreVanillaModItems.GOLDHAMMER.get());
				tabData.accept(MoreVanillaModItems.DIAMONDHAMMER.get());
				tabData.accept(MoreVanillaModItems.NETHERITEHAMMER.get());
				tabData.accept(MoreVanillaModItems.WOODENEXAVATOR.get());
				tabData.accept(MoreVanillaModItems.STONE_EXAVATOR.get());
				tabData.accept(MoreVanillaModItems.IRON_EXAVATOR.get());
				tabData.accept(MoreVanillaModItems.GOLDEN_EXAVATOR.get());
				tabData.accept(MoreVanillaModItems.DIAMOND_EXAVATOR.get());
				tabData.accept(MoreVanillaModItems.NETHERITE_EXAVATOR.get());
				tabData.accept(MoreVanillaModItems.ENDERITEINGOT.get());
				tabData.accept(MoreVanillaModItems.ENDERITESCRAP.get());
				tabData.accept(MoreVanillaModBlocks.ENDERITEORE.get().asItem());
				tabData.accept(MoreVanillaModItems.ENDERITE_PICKAXE.get());
				tabData.accept(MoreVanillaModItems.ENDERITE_AXE.get());
				tabData.accept(MoreVanillaModItems.ENDERITE_SWORD.get());
				tabData.accept(MoreVanillaModItems.ENDERITE_SHOVEL.get());
				tabData.accept(MoreVanillaModItems.ENDERITE_HOE.get());
				tabData.accept(MoreVanillaModItems.ADAPAXELENDERITE.get());
				tabData.accept(MoreVanillaModItems.ENDERITEHAMMER.get());
				tabData.accept(MoreVanillaModItems.ENDERITE_EXAVATOR.get());
				tabData.accept(MoreVanillaModItems.ENDERITE_ARMOR_HELMET.get());
				tabData.accept(MoreVanillaModItems.ENDERITE_ARMOR_CHESTPLATE.get());
				tabData.accept(MoreVanillaModItems.ENDERITE_ARMOR_LEGGINGS.get());
				tabData.accept(MoreVanillaModItems.ENDERITE_ARMOR_BOOTS.get());
				tabData.accept(MoreVanillaModBlocks.ENDERITEBLOCK.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERPEARLORE.get().asItem());
				tabData.accept(MoreVanillaModBlocks.CAVEBLOCK.get().asItem());
				tabData.accept(MoreVanillaModItems.BOSSOFENDERITEPHASE1_SPAWN_EGG.get());
				tabData.accept(MoreVanillaModItems.SBIREBOSSENDERITE_SPAWN_EGG.get());
				tabData.accept(MoreVanillaModBlocks.PLANTEOFENDERITE.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDSTONEMODIFIED.get().asItem());
				tabData.accept(MoreVanillaModItems.ENDERITEDIMENSION.get());
				tabData.accept(MoreVanillaModBlocks.LUCKYBLOCK.get().asItem());
				tabData.accept(MoreVanillaModBlocks.NETHERITE_LUCKYBLOCK.get().asItem());
				tabData.accept(MoreVanillaModItems.ENDERITEAPPLE.get());
				tabData.accept(MoreVanillaModItems.NETHERITEAPPLE.get());
				tabData.accept(MoreVanillaModBlocks.ENDGRASS.get().asItem());
				tabData.accept(MoreVanillaModBlocks.SHINYENDERBLOCK.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDSTONECOMPACT.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDWOOD.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDPLANKS.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDLEAVES.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDROCK.get().asItem());
				tabData.accept(MoreVanillaModBlocks.BARREL.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDSLAB.get().asItem());
				tabData.accept(MoreVanillaModBlocks.EDNROCKSLAB.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDPLANKSSTAIRS.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDROCKSTAIRS.get().asItem());
				tabData.accept(MoreVanillaModItems.BACKPACK.get());
				tabData.accept(MoreVanillaModItems.GREENFIREBALLPOWER.get());
				tabData.accept(MoreVanillaModItems.DYNAMITEM.get());
				tabData.accept(MoreVanillaModBlocks.ENDBARRIER.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDGATE.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDDIRT.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDTRAPEDOOR.get().asItem());
				tabData.accept(MoreVanillaModBlocks.SPAWNERBOSS.get().asItem());
				tabData.accept(MoreVanillaModItems.ENDSILVER_SPAWN_EGG.get());
				tabData.accept(MoreVanillaModBlocks.FAR_END_WOOD.get().asItem());
				tabData.accept(MoreVanillaModBlocks.FAR_END_LOG.get().asItem());
				tabData.accept(MoreVanillaModBlocks.FAR_END_PLANKS.get().asItem());
				tabData.accept(MoreVanillaModBlocks.FAR_END_LEAVES.get().asItem());
				tabData.accept(MoreVanillaModBlocks.FAR_END_STAIRS.get().asItem());
				tabData.accept(MoreVanillaModBlocks.FAR_END_SLAB.get().asItem());
				tabData.accept(MoreVanillaModBlocks.FAR_END_FENCE.get().asItem());
				tabData.accept(MoreVanillaModBlocks.FAR_END_FENCE_GATE.get().asItem());
				tabData.accept(MoreVanillaModBlocks.FAR_END_PRESSURE_PLATE.get().asItem());
				tabData.accept(MoreVanillaModBlocks.FAR_END_BUTTON.get().asItem());
				tabData.accept(MoreVanillaModBlocks.FARENDGRASS.get().asItem());
				tabData.accept(MoreVanillaModBlocks.FARENDDIRT.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERZONE_WOOD.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERZONE_LOG.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERZONE_PLANKS.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERZONE_LEAVES.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERZONE_STAIRS.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERZONE_SLAB.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERZONE_FENCE.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERZONE_FENCE_GATE.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERZONE_PRESSURE_PLATE.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERZONE_BUTTON.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERZONEDIRT.get().asItem());
				tabData.accept(MoreVanillaModBlocks.ENDERZONEGRASS.get().asItem());
				tabData.accept(MoreVanillaModItems.LOKI.get());
				tabData.accept(MoreVanillaModItems.BATTLE.get());
			}).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> UPGRADENETHERITE = REGISTRY.register("upgradenetherite",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.more_vanilla.upgradenetherite")).icon(() -> new ItemStack(MoreVanillaModItems.UPGRADENETHERITEIRONINGOT.get())).displayItems((parameters, tabData) -> {
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEIRONINGOT.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEGOLDINGOT.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEEMERAULDINGOT.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEDIAMONDINGOT.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEIRON_ARMOR_HELMET.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEIRON_ARMOR_CHESTPLATE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEIRON_ARMOR_LEGGINGS.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEIRON_ARMOR_BOOTS.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEIRON_PICKAXE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEIRON_AXE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEIRON_SWORD.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEIRON_SHOVEL.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEIRON_HOE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEGOLD_HELMET.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEGOLD_CHESTPLATE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEGOLD_LEGGINGS.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEGOLD_BOOTS.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEGOLDPICKAXE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEGOLDAXE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEGOLDSWORD.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEGOLDSHOVEL.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEGOLDHOE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEEMERAULD_HELMET.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEEMERAULD_CHESTPLATE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEEMERAULD_LEGGINGS.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEEMERAULD_BOOTS.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEEMERAULDPICKAXE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEEMERAULDAXE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEEMERAULDSWORD.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEEMERAULDSHOVEL.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEEMERAULDHOE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEDIAMOND_HELMET.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEDIAMOND_CHESTPLATE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEDIAMOND_LEGGINGS.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEDIAMOND_BOOTS.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEDIAMONDPICKAXE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEDIAMONDAXE.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEDIAMONDSWORD.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEDIAMONDSHOVEL.get());
				tabData.accept(MoreVanillaModItems.UPGRADENETHERITEDIAMONDHOE.get());
				tabData.accept(MoreVanillaModBlocks.UPGRADENETHERITEBLOCKIRON.get().asItem());
				tabData.accept(MoreVanillaModBlocks.UPGRADENETHERITEBLOCKGOLD.get().asItem());
				tabData.accept(MoreVanillaModBlocks.UPGRADENETHERITEBLOCKEMERAULD.get().asItem());
				tabData.accept(MoreVanillaModBlocks.UPGRADENETHERITEBLOCKDIAMOND.get().asItem());
				tabData.accept(MoreVanillaModItems.ADAPAXELUPGRADEIRONNETHERITE.get());
				tabData.accept(MoreVanillaModItems.UPGRADEIRONNETHERITEHAMMER.get());
				tabData.accept(MoreVanillaModItems.UPGRADEIRONNETHERITEEXAVATOR.get());
				tabData.accept(MoreVanillaModItems.ADAPAXELUPGRADEGOLDNETHERITE.get());
				tabData.accept(MoreVanillaModItems.UPGRADEGOLDNETHERITEHAMMER.get());
				tabData.accept(MoreVanillaModItems.UPGRADEGOLDNETHERITEEXAVATOR.get());
				tabData.accept(MoreVanillaModItems.ADAPAXELUPGRADEEMERAULDNETHERITE.get());
				tabData.accept(MoreVanillaModItems.UPGRADEEMERAULDNETHERITEHAMMER.get());
				tabData.accept(MoreVanillaModItems.UPGRADEEMERAULDNETHERITEEXAVATOR.get());
				tabData.accept(MoreVanillaModItems.ADAPAXELUPGRADEDIAMONDNETHERITE.get());
				tabData.accept(MoreVanillaModItems.UPGRADEDIAMONDNETHERITEHAMMER.get());
				tabData.accept(MoreVanillaModItems.UPGRADEDIAMONDNETHERITEEXAVATOR.get());
				tabData.accept(MoreVanillaModItems.UPGRADEIRONBOSS_SPAWN_EGG.get());
				tabData.accept(MoreVanillaModItems.UPGRADEGOLDBOSS_SPAWN_EGG.get());
				tabData.accept(MoreVanillaModItems.UPGRADEEMERALDBOSS_SPAWN_EGG.get());
				tabData.accept(MoreVanillaModItems.UPGRADEDIAMONDBOSS_SPAWN_EGG.get());
			}).withTabsBefore(THE_DEMO_NMOD.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MOREGEMS = REGISTRY.register("moregems",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.more_vanilla.moregems")).icon(() -> new ItemStack(MoreVanillaModItems.SAPPHIRE.get())).displayItems((parameters, tabData) -> {
				tabData.accept(MoreVanillaModItems.ADAPAXELEMERALD.get());
				tabData.accept(MoreVanillaModItems.ADAPAXELRUBY.get());
				tabData.accept(MoreVanillaModItems.ADAPAXELSAPPHIRE.get());
				tabData.accept(MoreVanillaModItems.RUBY.get());
				tabData.accept(MoreVanillaModItems.SAPPHIRE.get());
				tabData.accept(MoreVanillaModItems.SAPPHIREPICKAXE.get());
				tabData.accept(MoreVanillaModItems.RUBYPICKAXE.get());
				tabData.accept(MoreVanillaModItems.EMERALDPICKAXE.get());
				tabData.accept(MoreVanillaModItems.SAPPHIRESHOVEL.get());
				tabData.accept(MoreVanillaModItems.SAPPHIREAXE.get());
				tabData.accept(MoreVanillaModItems.SAPPHIREHOE.get());
				tabData.accept(MoreVanillaModItems.SAPPHIRESWORD.get());
				tabData.accept(MoreVanillaModItems.RUBYSWORD.get());
				tabData.accept(MoreVanillaModItems.EMERALDSWORD.get());
				tabData.accept(MoreVanillaModItems.EMERALDSHOVEL.get());
				tabData.accept(MoreVanillaModItems.EMERALDAXE.get());
				tabData.accept(MoreVanillaModItems.EMERALDHOE.get());
				tabData.accept(MoreVanillaModItems.RUBYSHOVEL.get());
				tabData.accept(MoreVanillaModItems.RUBYAXE.get());
				tabData.accept(MoreVanillaModItems.RUBYHOE.get());
				tabData.accept(MoreVanillaModItems.RUBYHAMMER.get());
				tabData.accept(MoreVanillaModItems.RUBYEXAVATOR.get());
				tabData.accept(MoreVanillaModItems.SAPPHIREHAMMER.get());
				tabData.accept(MoreVanillaModItems.EMERALDHAMMER.get());
				tabData.accept(MoreVanillaModItems.SAPPHIREEXAVATOR.get());
				tabData.accept(MoreVanillaModItems.EMERALDEXAVATOR.get());
				tabData.accept(MoreVanillaModBlocks.RUBYORE.get().asItem());
				tabData.accept(MoreVanillaModBlocks.SAPPHIREORE.get().asItem());
				tabData.accept(MoreVanillaModItems.EMERALDARMOR_HELMET.get());
				tabData.accept(MoreVanillaModItems.EMERALDARMOR_CHESTPLATE.get());
				tabData.accept(MoreVanillaModItems.EMERALDARMOR_LEGGINGS.get());
				tabData.accept(MoreVanillaModItems.EMERALDARMOR_BOOTS.get());
				tabData.accept(MoreVanillaModItems.SAPPHIREARMOR_HELMET.get());
				tabData.accept(MoreVanillaModItems.SAPPHIREARMOR_CHESTPLATE.get());
				tabData.accept(MoreVanillaModItems.SAPPHIREARMOR_LEGGINGS.get());
				tabData.accept(MoreVanillaModItems.SAPPHIREARMOR_BOOTS.get());
				tabData.accept(MoreVanillaModItems.RUBYARMOR_HELMET.get());
				tabData.accept(MoreVanillaModItems.RUBYARMOR_CHESTPLATE.get());
				tabData.accept(MoreVanillaModItems.RUBYARMOR_LEGGINGS.get());
				tabData.accept(MoreVanillaModItems.RUBYARMOR_BOOTS.get());
				tabData.accept(MoreVanillaModBlocks.RUBYBLOCK.get().asItem());
				tabData.accept(MoreVanillaModBlocks.SAPPHIREBLOCK.get().asItem());
			}).withTabsBefore(UPGRADENETHERITE.getId()).build());
}
