
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.more_vanilla.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.more_vanilla.item.inventory.BackpackInventoryCapability;
import net.mcreator.more_vanilla.item.WoodenhammerItem;
import net.mcreator.more_vanilla.item.WoodenexavatorItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteironingotItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteironSwordItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteironShovelItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteironPickaxeItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteironHoeItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteironAxeItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteironArmorItem;
import net.mcreator.more_vanilla.item.UpgradenetheritegoldswordItem;
import net.mcreator.more_vanilla.item.UpgradenetheritegoldshovelItem;
import net.mcreator.more_vanilla.item.UpgradenetheritegoldpickaxeItem;
import net.mcreator.more_vanilla.item.UpgradenetheritegoldingotItem;
import net.mcreator.more_vanilla.item.UpgradenetheritegoldhoeItem;
import net.mcreator.more_vanilla.item.UpgradenetheritegoldaxeItem;
import net.mcreator.more_vanilla.item.UpgradenetheritegoldItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteemerauldswordItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteemerauldshovelItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteemerauldpickaxeItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteemerauldingotItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteemerauldhoeItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteemerauldaxeItem;
import net.mcreator.more_vanilla.item.UpgradenetheriteemerauldItem;
import net.mcreator.more_vanilla.item.UpgradenetheritediamondswordItem;
import net.mcreator.more_vanilla.item.UpgradenetheritediamondshovelItem;
import net.mcreator.more_vanilla.item.UpgradenetheritediamondpickaxeItem;
import net.mcreator.more_vanilla.item.UpgradenetheritediamondingotItem;
import net.mcreator.more_vanilla.item.UpgradenetheritediamondhoeItem;
import net.mcreator.more_vanilla.item.UpgradenetheritediamondaxeItem;
import net.mcreator.more_vanilla.item.UpgradenetheritediamondItem;
import net.mcreator.more_vanilla.item.UpgradeironnetheritehammerItem;
import net.mcreator.more_vanilla.item.UpgradeironnetheriteItem;
import net.mcreator.more_vanilla.item.UpgradegoldnetheritehammerItem;
import net.mcreator.more_vanilla.item.UpgradegoldnetheriteexavatorItem;
import net.mcreator.more_vanilla.item.UpgradeemerauldnetheritehammerItem;
import net.mcreator.more_vanilla.item.UpgradeemerauldnetheriteexavatorItem;
import net.mcreator.more_vanilla.item.UpgradediamondnetheritehammerItem;
import net.mcreator.more_vanilla.item.UpgradediamondnetheriteexavatorItem;
import net.mcreator.more_vanilla.item.StonehammerItem;
import net.mcreator.more_vanilla.item.StoneExavatorItem;
import net.mcreator.more_vanilla.item.SapphireswordItem;
import net.mcreator.more_vanilla.item.SapphireshovelItem;
import net.mcreator.more_vanilla.item.SapphirepickaxeItem;
import net.mcreator.more_vanilla.item.SapphirehoeItem;
import net.mcreator.more_vanilla.item.SapphirehammerItem;
import net.mcreator.more_vanilla.item.SapphireexavatorItem;
import net.mcreator.more_vanilla.item.SapphireaxeItem;
import net.mcreator.more_vanilla.item.SapphirearmorItem;
import net.mcreator.more_vanilla.item.SapphireItem;
import net.mcreator.more_vanilla.item.RubyswordItem;
import net.mcreator.more_vanilla.item.RubyshovelItem;
import net.mcreator.more_vanilla.item.RubypickaxeItem;
import net.mcreator.more_vanilla.item.RubyhoeItem;
import net.mcreator.more_vanilla.item.RubyhammerItem;
import net.mcreator.more_vanilla.item.RubyexavatorItem;
import net.mcreator.more_vanilla.item.RubyaxeItem;
import net.mcreator.more_vanilla.item.RubyarmorItem;
import net.mcreator.more_vanilla.item.RubyItem;
import net.mcreator.more_vanilla.item.NetheritehammerItem;
import net.mcreator.more_vanilla.item.NetheriteappleItem;
import net.mcreator.more_vanilla.item.NetheriteExavatorItem;
import net.mcreator.more_vanilla.item.LokiItem;
import net.mcreator.more_vanilla.item.IronhammerItem;
import net.mcreator.more_vanilla.item.IronExavatorItem;
import net.mcreator.more_vanilla.item.GreenfireballpowerItem;
import net.mcreator.more_vanilla.item.GreenfireballItem;
import net.mcreator.more_vanilla.item.GoldhammerItem;
import net.mcreator.more_vanilla.item.GoldenExavatorItem;
import net.mcreator.more_vanilla.item.EnderitescrapItem;
import net.mcreator.more_vanilla.item.EnderiteingotItem;
import net.mcreator.more_vanilla.item.EnderitehammerItem;
import net.mcreator.more_vanilla.item.EnderitedimensionItem;
import net.mcreator.more_vanilla.item.EnderiteappleItem;
import net.mcreator.more_vanilla.item.EnderiteSwordItem;
import net.mcreator.more_vanilla.item.EnderiteShovelItem;
import net.mcreator.more_vanilla.item.EnderitePickaxeItem;
import net.mcreator.more_vanilla.item.EnderiteHoeItem;
import net.mcreator.more_vanilla.item.EnderiteExavatorItem;
import net.mcreator.more_vanilla.item.EnderiteAxeItem;
import net.mcreator.more_vanilla.item.EnderiteArmorItem;
import net.mcreator.more_vanilla.item.EmeraldswordItem;
import net.mcreator.more_vanilla.item.EmeraldshovelItem;
import net.mcreator.more_vanilla.item.EmeraldpickaxeItem;
import net.mcreator.more_vanilla.item.EmeraldhoeItem;
import net.mcreator.more_vanilla.item.EmeraldhammerItem;
import net.mcreator.more_vanilla.item.EmeraldexavatorItem;
import net.mcreator.more_vanilla.item.EmeraldaxeItem;
import net.mcreator.more_vanilla.item.EmeraldarmorItem;
import net.mcreator.more_vanilla.item.EauregeneranteItem;
import net.mcreator.more_vanilla.item.DynamitemItem;
import net.mcreator.more_vanilla.item.DynamiteItem;
import net.mcreator.more_vanilla.item.DiamondhammerItem;
import net.mcreator.more_vanilla.item.DiamondExavatorItem;
import net.mcreator.more_vanilla.item.BattleItem;
import net.mcreator.more_vanilla.item.BackpackItem;
import net.mcreator.more_vanilla.item.AdapaxelupgradeironnetheriteItem;
import net.mcreator.more_vanilla.item.AdapaxelupgradegoldnetheriteItem;
import net.mcreator.more_vanilla.item.AdapaxelupgradeemerauldnetheriteItem;
import net.mcreator.more_vanilla.item.AdapaxelupgradediamondnetheriteItem;
import net.mcreator.more_vanilla.item.AdapaxelstoneItem;
import net.mcreator.more_vanilla.item.AdapaxelsapphireItem;
import net.mcreator.more_vanilla.item.AdapaxelrubyItem;
import net.mcreator.more_vanilla.item.AdapaxelnetheriteItem;
import net.mcreator.more_vanilla.item.AdapaxelironItem;
import net.mcreator.more_vanilla.item.AdapaxelgoldItem;
import net.mcreator.more_vanilla.item.AdapaxelenderiteItem;
import net.mcreator.more_vanilla.item.AdapaxelemeraldItem;
import net.mcreator.more_vanilla.item.AdapaxeldiamondItem;
import net.mcreator.more_vanilla.item.AdapaxelItem;
import net.mcreator.more_vanilla.MoreVanillaMod;

@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD)
public class MoreVanillaModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(MoreVanillaMod.MODID);
	public static final DeferredItem<Item> EAUREGENERANTE_BUCKET = REGISTRY.register("eauregenerante_bucket", EauregeneranteItem::new);
	public static final DeferredItem<Item> ADAPAXEL = REGISTRY.register("adapaxel", AdapaxelItem::new);
	public static final DeferredItem<Item> ADAPAXELSTONE = REGISTRY.register("adapaxelstone", AdapaxelstoneItem::new);
	public static final DeferredItem<Item> ADAPAXELIRON = REGISTRY.register("adapaxeliron", AdapaxelironItem::new);
	public static final DeferredItem<Item> ADAPAXELGOLD = REGISTRY.register("adapaxelgold", AdapaxelgoldItem::new);
	public static final DeferredItem<Item> ADAPAXELDIAMOND = REGISTRY.register("adapaxeldiamond", AdapaxeldiamondItem::new);
	public static final DeferredItem<Item> ADAPAXELNETHERITE = REGISTRY.register("adapaxelnetherite", AdapaxelnetheriteItem::new);
	public static final DeferredItem<Item> WOODENHAMMER = REGISTRY.register("woodenhammer", WoodenhammerItem::new);
	public static final DeferredItem<Item> STONEHAMMER = REGISTRY.register("stonehammer", StonehammerItem::new);
	public static final DeferredItem<Item> IRONHAMMER = REGISTRY.register("ironhammer", IronhammerItem::new);
	public static final DeferredItem<Item> GOLDHAMMER = REGISTRY.register("goldhammer", GoldhammerItem::new);
	public static final DeferredItem<Item> DIAMONDHAMMER = REGISTRY.register("diamondhammer", DiamondhammerItem::new);
	public static final DeferredItem<Item> NETHERITEHAMMER = REGISTRY.register("netheritehammer", NetheritehammerItem::new);
	public static final DeferredItem<Item> WOODENEXAVATOR = REGISTRY.register("woodenexavator", WoodenexavatorItem::new);
	public static final DeferredItem<Item> STONE_EXAVATOR = REGISTRY.register("stone_exavator", StoneExavatorItem::new);
	public static final DeferredItem<Item> IRON_EXAVATOR = REGISTRY.register("iron_exavator", IronExavatorItem::new);
	public static final DeferredItem<Item> GOLDEN_EXAVATOR = REGISTRY.register("golden_exavator", GoldenExavatorItem::new);
	public static final DeferredItem<Item> DIAMOND_EXAVATOR = REGISTRY.register("diamond_exavator", DiamondExavatorItem::new);
	public static final DeferredItem<Item> NETHERITE_EXAVATOR = REGISTRY.register("netherite_exavator", NetheriteExavatorItem::new);
	public static final DeferredItem<Item> ENDERITEINGOT = REGISTRY.register("enderiteingot", EnderiteingotItem::new);
	public static final DeferredItem<Item> ENDERITESCRAP = REGISTRY.register("enderitescrap", EnderitescrapItem::new);
	public static final DeferredItem<Item> ENDERITEORE = block(MoreVanillaModBlocks.ENDERITEORE);
	public static final DeferredItem<Item> ENDERITE_PICKAXE = REGISTRY.register("enderite_pickaxe", EnderitePickaxeItem::new);
	public static final DeferredItem<Item> ENDERITE_AXE = REGISTRY.register("enderite_axe", EnderiteAxeItem::new);
	public static final DeferredItem<Item> ENDERITE_SWORD = REGISTRY.register("enderite_sword", EnderiteSwordItem::new);
	public static final DeferredItem<Item> ENDERITE_SHOVEL = REGISTRY.register("enderite_shovel", EnderiteShovelItem::new);
	public static final DeferredItem<Item> ENDERITE_HOE = REGISTRY.register("enderite_hoe", EnderiteHoeItem::new);
	public static final DeferredItem<Item> ADAPAXELENDERITE = REGISTRY.register("adapaxelenderite", AdapaxelenderiteItem::new);
	public static final DeferredItem<Item> ENDERITEHAMMER = REGISTRY.register("enderitehammer", EnderitehammerItem::new);
	public static final DeferredItem<Item> ENDERITE_EXAVATOR = REGISTRY.register("enderite_exavator", EnderiteExavatorItem::new);
	public static final DeferredItem<Item> ENDERITE_ARMOR_HELMET = REGISTRY.register("enderite_armor_helmet", EnderiteArmorItem.Helmet::new);
	public static final DeferredItem<Item> ENDERITE_ARMOR_CHESTPLATE = REGISTRY.register("enderite_armor_chestplate", EnderiteArmorItem.Chestplate::new);
	public static final DeferredItem<Item> ENDERITE_ARMOR_LEGGINGS = REGISTRY.register("enderite_armor_leggings", EnderiteArmorItem.Leggings::new);
	public static final DeferredItem<Item> ENDERITE_ARMOR_BOOTS = REGISTRY.register("enderite_armor_boots", EnderiteArmorItem.Boots::new);
	public static final DeferredItem<Item> ENDERITEBLOCK = block(MoreVanillaModBlocks.ENDERITEBLOCK);
	public static final DeferredItem<Item> ENDERPEARLORE = block(MoreVanillaModBlocks.ENDERPEARLORE);
	public static final DeferredItem<Item> CAVEBLOCK = block(MoreVanillaModBlocks.CAVEBLOCK);
	public static final DeferredItem<Item> BOSSOFENDERITEPHASE1_SPAWN_EGG = REGISTRY.register("bossofenderitephase1_spawn_egg", () -> new DeferredSpawnEggItem(MoreVanillaModEntities.BOSSOFENDERITEPHASE1, -16751104, -16764109, new Item.Properties()));
	public static final DeferredItem<Item> SBIREBOSSENDERITE_SPAWN_EGG = REGISTRY.register("sbirebossenderite_spawn_egg", () -> new DeferredSpawnEggItem(MoreVanillaModEntities.SBIREBOSSENDERITE, -16764109, -16764109, new Item.Properties()));
	public static final DeferredItem<Item> PLANTEOFENDERITE = block(MoreVanillaModBlocks.PLANTEOFENDERITE);
	public static final DeferredItem<Item> ENDSTONEMODIFIED = block(MoreVanillaModBlocks.ENDSTONEMODIFIED);
	public static final DeferredItem<Item> ENDERITEDIMENSION = REGISTRY.register("enderitedimension", EnderitedimensionItem::new);
	public static final DeferredItem<Item> LUCKYBLOCK = block(MoreVanillaModBlocks.LUCKYBLOCK);
	public static final DeferredItem<Item> NETHERITE_LUCKYBLOCK = block(MoreVanillaModBlocks.NETHERITE_LUCKYBLOCK);
	public static final DeferredItem<Item> UPGRADENETHERITEIRONINGOT = REGISTRY.register("upgradenetheriteironingot", UpgradenetheriteironingotItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEGOLDINGOT = REGISTRY.register("upgradenetheritegoldingot", UpgradenetheritegoldingotItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEEMERAULDINGOT = REGISTRY.register("upgradenetheriteemerauldingot", UpgradenetheriteemerauldingotItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEDIAMONDINGOT = REGISTRY.register("upgradenetheritediamondingot", UpgradenetheritediamondingotItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEIRON_ARMOR_HELMET = REGISTRY.register("upgradenetheriteiron_armor_helmet", UpgradenetheriteironArmorItem.Helmet::new);
	public static final DeferredItem<Item> UPGRADENETHERITEIRON_ARMOR_CHESTPLATE = REGISTRY.register("upgradenetheriteiron_armor_chestplate", UpgradenetheriteironArmorItem.Chestplate::new);
	public static final DeferredItem<Item> UPGRADENETHERITEIRON_ARMOR_LEGGINGS = REGISTRY.register("upgradenetheriteiron_armor_leggings", UpgradenetheriteironArmorItem.Leggings::new);
	public static final DeferredItem<Item> UPGRADENETHERITEIRON_ARMOR_BOOTS = REGISTRY.register("upgradenetheriteiron_armor_boots", UpgradenetheriteironArmorItem.Boots::new);
	public static final DeferredItem<Item> UPGRADENETHERITEIRON_PICKAXE = REGISTRY.register("upgradenetheriteiron_pickaxe", UpgradenetheriteironPickaxeItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEIRON_AXE = REGISTRY.register("upgradenetheriteiron_axe", UpgradenetheriteironAxeItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEIRON_SWORD = REGISTRY.register("upgradenetheriteiron_sword", UpgradenetheriteironSwordItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEIRON_SHOVEL = REGISTRY.register("upgradenetheriteiron_shovel", UpgradenetheriteironShovelItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEIRON_HOE = REGISTRY.register("upgradenetheriteiron_hoe", UpgradenetheriteironHoeItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEGOLD_HELMET = REGISTRY.register("upgradenetheritegold_helmet", UpgradenetheritegoldItem.Helmet::new);
	public static final DeferredItem<Item> UPGRADENETHERITEGOLD_CHESTPLATE = REGISTRY.register("upgradenetheritegold_chestplate", UpgradenetheritegoldItem.Chestplate::new);
	public static final DeferredItem<Item> UPGRADENETHERITEGOLD_LEGGINGS = REGISTRY.register("upgradenetheritegold_leggings", UpgradenetheritegoldItem.Leggings::new);
	public static final DeferredItem<Item> UPGRADENETHERITEGOLD_BOOTS = REGISTRY.register("upgradenetheritegold_boots", UpgradenetheritegoldItem.Boots::new);
	public static final DeferredItem<Item> UPGRADENETHERITEGOLDPICKAXE = REGISTRY.register("upgradenetheritegoldpickaxe", UpgradenetheritegoldpickaxeItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEGOLDAXE = REGISTRY.register("upgradenetheritegoldaxe", UpgradenetheritegoldaxeItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEGOLDSWORD = REGISTRY.register("upgradenetheritegoldsword", UpgradenetheritegoldswordItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEGOLDSHOVEL = REGISTRY.register("upgradenetheritegoldshovel", UpgradenetheritegoldshovelItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEGOLDHOE = REGISTRY.register("upgradenetheritegoldhoe", UpgradenetheritegoldhoeItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEEMERAULD_HELMET = REGISTRY.register("upgradenetheriteemerauld_helmet", UpgradenetheriteemerauldItem.Helmet::new);
	public static final DeferredItem<Item> UPGRADENETHERITEEMERAULD_CHESTPLATE = REGISTRY.register("upgradenetheriteemerauld_chestplate", UpgradenetheriteemerauldItem.Chestplate::new);
	public static final DeferredItem<Item> UPGRADENETHERITEEMERAULD_LEGGINGS = REGISTRY.register("upgradenetheriteemerauld_leggings", UpgradenetheriteemerauldItem.Leggings::new);
	public static final DeferredItem<Item> UPGRADENETHERITEEMERAULD_BOOTS = REGISTRY.register("upgradenetheriteemerauld_boots", UpgradenetheriteemerauldItem.Boots::new);
	public static final DeferredItem<Item> UPGRADENETHERITEEMERAULDPICKAXE = REGISTRY.register("upgradenetheriteemerauldpickaxe", UpgradenetheriteemerauldpickaxeItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEEMERAULDAXE = REGISTRY.register("upgradenetheriteemerauldaxe", UpgradenetheriteemerauldaxeItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEEMERAULDSWORD = REGISTRY.register("upgradenetheriteemerauldsword", UpgradenetheriteemerauldswordItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEEMERAULDSHOVEL = REGISTRY.register("upgradenetheriteemerauldshovel", UpgradenetheriteemerauldshovelItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEEMERAULDHOE = REGISTRY.register("upgradenetheriteemerauldhoe", UpgradenetheriteemerauldhoeItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEDIAMOND_HELMET = REGISTRY.register("upgradenetheritediamond_helmet", UpgradenetheritediamondItem.Helmet::new);
	public static final DeferredItem<Item> UPGRADENETHERITEDIAMOND_CHESTPLATE = REGISTRY.register("upgradenetheritediamond_chestplate", UpgradenetheritediamondItem.Chestplate::new);
	public static final DeferredItem<Item> UPGRADENETHERITEDIAMOND_LEGGINGS = REGISTRY.register("upgradenetheritediamond_leggings", UpgradenetheritediamondItem.Leggings::new);
	public static final DeferredItem<Item> UPGRADENETHERITEDIAMOND_BOOTS = REGISTRY.register("upgradenetheritediamond_boots", UpgradenetheritediamondItem.Boots::new);
	public static final DeferredItem<Item> UPGRADENETHERITEDIAMONDPICKAXE = REGISTRY.register("upgradenetheritediamondpickaxe", UpgradenetheritediamondpickaxeItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEDIAMONDAXE = REGISTRY.register("upgradenetheritediamondaxe", UpgradenetheritediamondaxeItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEDIAMONDSWORD = REGISTRY.register("upgradenetheritediamondsword", UpgradenetheritediamondswordItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEDIAMONDSHOVEL = REGISTRY.register("upgradenetheritediamondshovel", UpgradenetheritediamondshovelItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEDIAMONDHOE = REGISTRY.register("upgradenetheritediamondhoe", UpgradenetheritediamondhoeItem::new);
	public static final DeferredItem<Item> UPGRADENETHERITEBLOCKIRON = block(MoreVanillaModBlocks.UPGRADENETHERITEBLOCKIRON);
	public static final DeferredItem<Item> UPGRADENETHERITEBLOCKGOLD = block(MoreVanillaModBlocks.UPGRADENETHERITEBLOCKGOLD);
	public static final DeferredItem<Item> UPGRADENETHERITEBLOCKEMERAULD = block(MoreVanillaModBlocks.UPGRADENETHERITEBLOCKEMERAULD);
	public static final DeferredItem<Item> UPGRADENETHERITEBLOCKDIAMOND = block(MoreVanillaModBlocks.UPGRADENETHERITEBLOCKDIAMOND);
	public static final DeferredItem<Item> ENDERITEAPPLE = REGISTRY.register("enderiteapple", EnderiteappleItem::new);
	public static final DeferredItem<Item> NETHERITEAPPLE = REGISTRY.register("netheriteapple", NetheriteappleItem::new);
	public static final DeferredItem<Item> ADAPAXELUPGRADEIRONNETHERITE = REGISTRY.register("adapaxelupgradeironnetherite", AdapaxelupgradeironnetheriteItem::new);
	public static final DeferredItem<Item> UPGRADEIRONNETHERITEHAMMER = REGISTRY.register("upgradeironnetheritehammer", UpgradeironnetheritehammerItem::new);
	public static final DeferredItem<Item> UPGRADEIRONNETHERITEEXAVATOR = REGISTRY.register("upgradeironnetheriteexavator", UpgradeironnetheriteItem::new);
	public static final DeferredItem<Item> ADAPAXELUPGRADEGOLDNETHERITE = REGISTRY.register("adapaxelupgradegoldnetherite", AdapaxelupgradegoldnetheriteItem::new);
	public static final DeferredItem<Item> UPGRADEGOLDNETHERITEHAMMER = REGISTRY.register("upgradegoldnetheritehammer", UpgradegoldnetheritehammerItem::new);
	public static final DeferredItem<Item> UPGRADEGOLDNETHERITEEXAVATOR = REGISTRY.register("upgradegoldnetheriteexavator", UpgradegoldnetheriteexavatorItem::new);
	public static final DeferredItem<Item> ADAPAXELUPGRADEEMERAULDNETHERITE = REGISTRY.register("adapaxelupgradeemerauldnetherite", AdapaxelupgradeemerauldnetheriteItem::new);
	public static final DeferredItem<Item> UPGRADEEMERAULDNETHERITEHAMMER = REGISTRY.register("upgradeemerauldnetheritehammer", UpgradeemerauldnetheritehammerItem::new);
	public static final DeferredItem<Item> UPGRADEEMERAULDNETHERITEEXAVATOR = REGISTRY.register("upgradeemerauldnetheriteexavator", UpgradeemerauldnetheriteexavatorItem::new);
	public static final DeferredItem<Item> ADAPAXELUPGRADEDIAMONDNETHERITE = REGISTRY.register("adapaxelupgradediamondnetherite", AdapaxelupgradediamondnetheriteItem::new);
	public static final DeferredItem<Item> UPGRADEDIAMONDNETHERITEHAMMER = REGISTRY.register("upgradediamondnetheritehammer", UpgradediamondnetheritehammerItem::new);
	public static final DeferredItem<Item> UPGRADEDIAMONDNETHERITEEXAVATOR = REGISTRY.register("upgradediamondnetheriteexavator", UpgradediamondnetheriteexavatorItem::new);
	public static final DeferredItem<Item> ADAPAXELEMERALD = REGISTRY.register("adapaxelemerald", AdapaxelemeraldItem::new);
	public static final DeferredItem<Item> ADAPAXELRUBY = REGISTRY.register("adapaxelruby", AdapaxelrubyItem::new);
	public static final DeferredItem<Item> ADAPAXELSAPPHIRE = REGISTRY.register("adapaxelsapphire", AdapaxelsapphireItem::new);
	public static final DeferredItem<Item> RUBY = REGISTRY.register("ruby", RubyItem::new);
	public static final DeferredItem<Item> SAPPHIRE = REGISTRY.register("sapphire", SapphireItem::new);
	public static final DeferredItem<Item> SAPPHIREPICKAXE = REGISTRY.register("sapphirepickaxe", SapphirepickaxeItem::new);
	public static final DeferredItem<Item> RUBYPICKAXE = REGISTRY.register("rubypickaxe", RubypickaxeItem::new);
	public static final DeferredItem<Item> EMERALDPICKAXE = REGISTRY.register("emeraldpickaxe", EmeraldpickaxeItem::new);
	public static final DeferredItem<Item> SAPPHIRESHOVEL = REGISTRY.register("sapphireshovel", SapphireshovelItem::new);
	public static final DeferredItem<Item> SAPPHIREAXE = REGISTRY.register("sapphireaxe", SapphireaxeItem::new);
	public static final DeferredItem<Item> SAPPHIREHOE = REGISTRY.register("sapphirehoe", SapphirehoeItem::new);
	public static final DeferredItem<Item> SAPPHIRESWORD = REGISTRY.register("sapphiresword", SapphireswordItem::new);
	public static final DeferredItem<Item> RUBYSWORD = REGISTRY.register("rubysword", RubyswordItem::new);
	public static final DeferredItem<Item> EMERALDSWORD = REGISTRY.register("emeraldsword", EmeraldswordItem::new);
	public static final DeferredItem<Item> EMERALDSHOVEL = REGISTRY.register("emeraldshovel", EmeraldshovelItem::new);
	public static final DeferredItem<Item> EMERALDAXE = REGISTRY.register("emeraldaxe", EmeraldaxeItem::new);
	public static final DeferredItem<Item> EMERALDHOE = REGISTRY.register("emeraldhoe", EmeraldhoeItem::new);
	public static final DeferredItem<Item> RUBYSHOVEL = REGISTRY.register("rubyshovel", RubyshovelItem::new);
	public static final DeferredItem<Item> RUBYAXE = REGISTRY.register("rubyaxe", RubyaxeItem::new);
	public static final DeferredItem<Item> RUBYHOE = REGISTRY.register("rubyhoe", RubyhoeItem::new);
	public static final DeferredItem<Item> RUBYHAMMER = REGISTRY.register("rubyhammer", RubyhammerItem::new);
	public static final DeferredItem<Item> RUBYEXAVATOR = REGISTRY.register("rubyexavator", RubyexavatorItem::new);
	public static final DeferredItem<Item> SAPPHIREHAMMER = REGISTRY.register("sapphirehammer", SapphirehammerItem::new);
	public static final DeferredItem<Item> EMERALDHAMMER = REGISTRY.register("emeraldhammer", EmeraldhammerItem::new);
	public static final DeferredItem<Item> SAPPHIREEXAVATOR = REGISTRY.register("sapphireexavator", SapphireexavatorItem::new);
	public static final DeferredItem<Item> EMERALDEXAVATOR = REGISTRY.register("emeraldexavator", EmeraldexavatorItem::new);
	public static final DeferredItem<Item> RUBYORE = block(MoreVanillaModBlocks.RUBYORE);
	public static final DeferredItem<Item> SAPPHIREORE = block(MoreVanillaModBlocks.SAPPHIREORE);
	public static final DeferredItem<Item> EMERALDARMOR_HELMET = REGISTRY.register("emeraldarmor_helmet", EmeraldarmorItem.Helmet::new);
	public static final DeferredItem<Item> EMERALDARMOR_CHESTPLATE = REGISTRY.register("emeraldarmor_chestplate", EmeraldarmorItem.Chestplate::new);
	public static final DeferredItem<Item> EMERALDARMOR_LEGGINGS = REGISTRY.register("emeraldarmor_leggings", EmeraldarmorItem.Leggings::new);
	public static final DeferredItem<Item> EMERALDARMOR_BOOTS = REGISTRY.register("emeraldarmor_boots", EmeraldarmorItem.Boots::new);
	public static final DeferredItem<Item> SAPPHIREARMOR_HELMET = REGISTRY.register("sapphirearmor_helmet", SapphirearmorItem.Helmet::new);
	public static final DeferredItem<Item> SAPPHIREARMOR_CHESTPLATE = REGISTRY.register("sapphirearmor_chestplate", SapphirearmorItem.Chestplate::new);
	public static final DeferredItem<Item> SAPPHIREARMOR_LEGGINGS = REGISTRY.register("sapphirearmor_leggings", SapphirearmorItem.Leggings::new);
	public static final DeferredItem<Item> SAPPHIREARMOR_BOOTS = REGISTRY.register("sapphirearmor_boots", SapphirearmorItem.Boots::new);
	public static final DeferredItem<Item> RUBYARMOR_HELMET = REGISTRY.register("rubyarmor_helmet", RubyarmorItem.Helmet::new);
	public static final DeferredItem<Item> RUBYARMOR_CHESTPLATE = REGISTRY.register("rubyarmor_chestplate", RubyarmorItem.Chestplate::new);
	public static final DeferredItem<Item> RUBYARMOR_LEGGINGS = REGISTRY.register("rubyarmor_leggings", RubyarmorItem.Leggings::new);
	public static final DeferredItem<Item> RUBYARMOR_BOOTS = REGISTRY.register("rubyarmor_boots", RubyarmorItem.Boots::new);
	public static final DeferredItem<Item> RUBYBLOCK = block(MoreVanillaModBlocks.RUBYBLOCK);
	public static final DeferredItem<Item> SAPPHIREBLOCK = block(MoreVanillaModBlocks.SAPPHIREBLOCK);
	public static final DeferredItem<Item> EMERALDORE = block(MoreVanillaModBlocks.EMERALDORE);
	public static final DeferredItem<Item> GREENFIREBALL = REGISTRY.register("greenfireball", GreenfireballItem::new);
	public static final DeferredItem<Item> DYNAMITEMUN = REGISTRY.register("dynamitemun", DynamiteItem::new);
	public static final DeferredItem<Item> UPGRADEIRONBOSS_SPAWN_EGG = REGISTRY.register("upgradeironboss_spawn_egg", () -> new DeferredSpawnEggItem(MoreVanillaModEntities.UPGRADEIRONBOSS, -16777216, -3355444, new Item.Properties()));
	public static final DeferredItem<Item> UPGRADEGOLDBOSS_SPAWN_EGG = REGISTRY.register("upgradegoldboss_spawn_egg", () -> new DeferredSpawnEggItem(MoreVanillaModEntities.UPGRADEGOLDBOSS, -16777216, -256, new Item.Properties()));
	public static final DeferredItem<Item> UPGRADEEMERALDBOSS_SPAWN_EGG = REGISTRY.register("upgradeemeraldboss_spawn_egg", () -> new DeferredSpawnEggItem(MoreVanillaModEntities.UPGRADEEMERALDBOSS, -16777216, -13382656, new Item.Properties()));
	public static final DeferredItem<Item> UPGRADEDIAMONDBOSS_SPAWN_EGG = REGISTRY.register("upgradediamondboss_spawn_egg", () -> new DeferredSpawnEggItem(MoreVanillaModEntities.UPGRADEDIAMONDBOSS, -16777216, -16724788, new Item.Properties()));
	public static final DeferredItem<Item> ENDGRASS = block(MoreVanillaModBlocks.ENDGRASS);
	public static final DeferredItem<Item> SHINYENDERBLOCK = block(MoreVanillaModBlocks.SHINYENDERBLOCK);
	public static final DeferredItem<Item> ENDSTONECOMPACT = block(MoreVanillaModBlocks.ENDSTONECOMPACT);
	public static final DeferredItem<Item> ENDWOOD = block(MoreVanillaModBlocks.ENDWOOD);
	public static final DeferredItem<Item> ENDPLANKS = block(MoreVanillaModBlocks.ENDPLANKS);
	public static final DeferredItem<Item> ENDLEAVES = block(MoreVanillaModBlocks.ENDLEAVES);
	public static final DeferredItem<Item> ENDROCK = block(MoreVanillaModBlocks.ENDROCK);
	public static final DeferredItem<Item> BARREL = block(MoreVanillaModBlocks.BARREL);
	public static final DeferredItem<Item> ENDSLAB = block(MoreVanillaModBlocks.ENDSLAB);
	public static final DeferredItem<Item> EDNROCKSLAB = block(MoreVanillaModBlocks.EDNROCKSLAB);
	public static final DeferredItem<Item> ENDPLANKSSTAIRS = block(MoreVanillaModBlocks.ENDPLANKSSTAIRS);
	public static final DeferredItem<Item> ENDROCKSTAIRS = block(MoreVanillaModBlocks.ENDROCKSTAIRS);
	public static final DeferredItem<Item> BACKPACK = REGISTRY.register("backpack", BackpackItem::new);
	public static final DeferredItem<Item> GREENFIREBALLPOWER = REGISTRY.register("greenfireballpower", GreenfireballpowerItem::new);
	public static final DeferredItem<Item> DYNAMITEM = REGISTRY.register("dynamitem", DynamitemItem::new);
	public static final DeferredItem<Item> ENDBARRIER = block(MoreVanillaModBlocks.ENDBARRIER);
	public static final DeferredItem<Item> ENDGATE = block(MoreVanillaModBlocks.ENDGATE);
	public static final DeferredItem<Item> ENDDIRT = block(MoreVanillaModBlocks.ENDDIRT);
	public static final DeferredItem<Item> ENDTRAPEDOOR = block(MoreVanillaModBlocks.ENDTRAPEDOOR);
	public static final DeferredItem<Item> SPAWNERBOSS = block(MoreVanillaModBlocks.SPAWNERBOSS);
	public static final DeferredItem<Item> ENDSILVER_SPAWN_EGG = REGISTRY.register("endsilver_spawn_egg", () -> new DeferredSpawnEggItem(MoreVanillaModEntities.ENDSILVER, -16738048, -16764160, new Item.Properties()));
	public static final DeferredItem<Item> FAR_END_WOOD = block(MoreVanillaModBlocks.FAR_END_WOOD);
	public static final DeferredItem<Item> FAR_END_LOG = block(MoreVanillaModBlocks.FAR_END_LOG);
	public static final DeferredItem<Item> FAR_END_PLANKS = block(MoreVanillaModBlocks.FAR_END_PLANKS);
	public static final DeferredItem<Item> FAR_END_LEAVES = block(MoreVanillaModBlocks.FAR_END_LEAVES);
	public static final DeferredItem<Item> FAR_END_STAIRS = block(MoreVanillaModBlocks.FAR_END_STAIRS);
	public static final DeferredItem<Item> FAR_END_SLAB = block(MoreVanillaModBlocks.FAR_END_SLAB);
	public static final DeferredItem<Item> FAR_END_FENCE = block(MoreVanillaModBlocks.FAR_END_FENCE);
	public static final DeferredItem<Item> FAR_END_FENCE_GATE = block(MoreVanillaModBlocks.FAR_END_FENCE_GATE);
	public static final DeferredItem<Item> FAR_END_PRESSURE_PLATE = block(MoreVanillaModBlocks.FAR_END_PRESSURE_PLATE);
	public static final DeferredItem<Item> FAR_END_BUTTON = block(MoreVanillaModBlocks.FAR_END_BUTTON);
	public static final DeferredItem<Item> FARENDGRASS = block(MoreVanillaModBlocks.FARENDGRASS);
	public static final DeferredItem<Item> FARENDDIRT = block(MoreVanillaModBlocks.FARENDDIRT);
	public static final DeferredItem<Item> ENDERZONE_WOOD = block(MoreVanillaModBlocks.ENDERZONE_WOOD);
	public static final DeferredItem<Item> ENDERZONE_LOG = block(MoreVanillaModBlocks.ENDERZONE_LOG);
	public static final DeferredItem<Item> ENDERZONE_PLANKS = block(MoreVanillaModBlocks.ENDERZONE_PLANKS);
	public static final DeferredItem<Item> ENDERZONE_LEAVES = block(MoreVanillaModBlocks.ENDERZONE_LEAVES);
	public static final DeferredItem<Item> ENDERZONE_STAIRS = block(MoreVanillaModBlocks.ENDERZONE_STAIRS);
	public static final DeferredItem<Item> ENDERZONE_SLAB = block(MoreVanillaModBlocks.ENDERZONE_SLAB);
	public static final DeferredItem<Item> ENDERZONE_FENCE = block(MoreVanillaModBlocks.ENDERZONE_FENCE);
	public static final DeferredItem<Item> ENDERZONE_FENCE_GATE = block(MoreVanillaModBlocks.ENDERZONE_FENCE_GATE);
	public static final DeferredItem<Item> ENDERZONE_PRESSURE_PLATE = block(MoreVanillaModBlocks.ENDERZONE_PRESSURE_PLATE);
	public static final DeferredItem<Item> ENDERZONE_BUTTON = block(MoreVanillaModBlocks.ENDERZONE_BUTTON);
	public static final DeferredItem<Item> ENDERZONEDIRT = block(MoreVanillaModBlocks.ENDERZONEDIRT);
	public static final DeferredItem<Item> ENDERZONEGRASS = block(MoreVanillaModBlocks.ENDERZONEGRASS);
	public static final DeferredItem<Item> LOKI = REGISTRY.register("loki", LokiItem::new);
	public static final DeferredItem<Item> BATTLE = REGISTRY.register("battle", BattleItem::new);
	public static final DeferredItem<Item> ELEVATOR = block(MoreVanillaModBlocks.ELEVATOR);

	// Start of user code block custom items
	// End of user code block custom items
	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new BackpackInventoryCapability(stack), BACKPACK.get());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
